# NegativeOS SLiM configuration

# Use NegativeOS Win95 theme
current_theme       negativeos-win95

# Default session
default_user
focus_password      no
auto_login          no

# Sessions available (Tab to cycle at login)
sessions            icewm,openbox

# Login commands
login_cmd           exec /bin/bash -login /etc/slim/Xsession %session
halt_cmd            /sbin/poweroff
reboot_cmd          /sbin/reboot
console_cmd         /usr/bin/xterm -C -fg white -bg black +sb -T "Console login" -e /bin/sh -c "/bin/login"

# Paths
screenshot_cmd      scrot /tmp/slim-screenshot.png
log_file            /var/log/slim.log
pid_file            /var/run/slim.pid
